### PR TITLE
Img

### PR DESCRIPTION
**Pull request by nichoth**
## Summary
Allow users to save an image when the feed is updated. This uses [a two step process](https://github.com/nichoth/blog/blob/img/src/pages/Editor.tsx#L81), where we first save an image file, then update the feed JSON object so that the given post contains the image file name.

**Is it possible to update both atomically?** So that you both save the image and update the JSON feed in one step? It is possible that the image could be saved & the blog feed not updated. And that's fine, it just means you would have a stray image sitting in ipfs. In that case you would re-post the post. You could use a hash of the image as the filename, that way it would automatically de-duplicate the images if you wrote the same one again when you re-post the post.

This will display images alongside the list of posts in the `Posts.tsx` file. We are using [Promise.all](https://github.com/nichoth/blog/blob/img/src/pages/Posts.tsx#L37) to get all images from ipfs and create URLs for them. This makes me think that some sort of pagination may be best, so you only load 1 page of images at a time, but that's a separate issue.

## Test plan (required)

There is [a unit test](https://github.com/nichoth/blog/blob/img/test/feed.spec.ts) that uses `jest`, you can run it with `npm test`

Also I set up `cypress` so that it is working, but haven't written any real tests with it yet. Run it with `npm run cypress`. This is for e2e testing (vs unit tests).

## typescript

~~Also i notice a type failure in [Posts.tsx](https://github.com/nichoth/blog/blob/img/src/pages/Posts.tsx#L22), at the `new Blob` line, but the app seems to compile and run~~

~~Type 'string | number | true | Record<string, unknown> | Uint8Array | Blob' is not assignable to type 'BlobPart'.
  Type 'number' is not assignable to type 'BlobPart'.ts(2322)~~
  
  Added 
  ```js
new Blob([content as BlobPart], {type: "image/jpeg"})
  ```
  to the file [Posts.tsx](https://github.com/nichoth/blog/blob/img/src/pages/Posts.tsx#L22), and now it's ok
  
  ----------------------------------------

~~Also see the call to setImages~~

This is not an error anymore. I added
```js
  var [images, setImages] = useState<(string | undefined)[]>([])
```
to the `Posts.tsx` file.

~~Argument of type '(string | undefined)[]' is not assignable to parameter of type 'SetStateAction<never[]>'.
  Type '(string | undefined)[]' is not assignable to type 'never[]'.
    Type 'string | undefined' is not assignable to type 'never'.
      Type 'undefined' is not assignable to type 'never'.ts(2345)~~

### CODE REVIEW

**Review by walkah — APPROVED** [review]
🚀 🚢  Looks good, thanks!

One minor request - can you remove the default / example tests from cypress? 

Then feel free to squash & merge when ready 🙌

**Comment by nichoth** [comment]
✅ rm default cypress

**Comment by walkah** [comment]
Hey @nichoth , can you rebase the package-lock.json conflict so we can get this merged? Thanks!

**Comment by nichoth** [comment]
I'm not totally sure what you mean about rebasing package-lock.json. I was thinking you would *want* to update package-lock.json. But anyway, I have checked out the version in the upstream/develop branch

**Comment by matheus23** [comment]
Not sure whether this is what @walkah ment, but when the package-lock.json file has conflicts, the best way to solve this issue is to do a `git merge` (get the merge conflicts in the files), then solve conflicts in the `package.json`, and then run `npm install --package-lock-only. (See docs: https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#resolving-lockfile-conflicts)

Npm will automatically fix the merge conflicts in the package-lock file for you.

**Comment by walkah** [comment]
thanks @matheus23 ! yes, that's exactly what I meant. There were some version updates in origin/develop (security release related) that caused conflicts between the package-lock.json file in the two branches.

**Comment by nichoth** [comment]
Ok I think I've done the resolution of package-lock

**Comment by walkah** [comment]
> Ok I think I've done the resolution of package-lock

Amazing! Time to hit the big green "Squash and merge" button whenever you're ready 😄

**Pull request merged**
